INSERT INTO `ratnacoi_zafrin`.`states` (`id`, `name`) VALUES (NULL, 'Andaman and Nicobar Islands');
INSERT INTO `ratnacoi_zafrin`.`states` (`id`, `name`) VALUES (NULL, 'Andhra Pradesh');
INSERT INTO `ratnacoi_zafrin`.`states` (`id`, `name`) VALUES (NULL, 'Arunachal Pradesh');
INSERT INTO `ratnacoi_zafrin`.`states` (`id`, `name`) VALUES (NULL, 'Assam');
INSERT INTO `ratnacoi_zafrin`.`states` (`id`, `name`) VALUES (NULL, 'Bihar');
INSERT INTO `ratnacoi_zafrin`.`states` (`id`, `name`) VALUES (NULL, 'Chandigarh');
INSERT INTO `ratnacoi_zafrin`.`states` (`id`, `name`) VALUES (NULL, 'Chhattisgarh');
INSERT INTO `ratnacoi_zafrin`.`states` (`id`, `name`) VALUES (NULL, 'Dadra and Nagar Haveli');
INSERT INTO `ratnacoi_zafrin`.`states` (`id`, `name`) VALUES (NULL, 'Daman and Diu');
INSERT INTO `ratnacoi_zafrin`.`states` (`id`, `name`) VALUES (NULL, 'Delhi');
INSERT INTO `ratnacoi_zafrin`.`states` (`id`, `name`) VALUES (NULL, 'Goa');
INSERT INTO `ratnacoi_zafrin`.`states` (`id`, `name`) VALUES (NULL, 'Gujarat');
INSERT INTO `ratnacoi_zafrin`.`states` (`id`, `name`) VALUES (NULL, 'Haryana');
INSERT INTO `ratnacoi_zafrin`.`states` (`id`, `name`) VALUES (NULL, 'Himachal Pradesh');
INSERT INTO `ratnacoi_zafrin`.`states` (`id`, `name`) VALUES (NULL, 'Jammu and Kashmir');
INSERT INTO `ratnacoi_zafrin`.`states` (`id`, `name`) VALUES (NULL, 'Jharkhand');
INSERT INTO `ratnacoi_zafrin`.`states` (`id`, `name`) VALUES (NULL, 'Karnataka');
INSERT INTO `ratnacoi_zafrin`.`states` (`id`, `name`) VALUES (NULL, 'Kerala');
INSERT INTO `ratnacoi_zafrin`.`states` (`id`, `name`) VALUES (NULL, 'Madhya Pradesh');
INSERT INTO `ratnacoi_zafrin`.`states` (`id`, `name`) VALUES (NULL, 'Maharashtra');
INSERT INTO `ratnacoi_zafrin`.`states` (`id`, `name`) VALUES (NULL, 'Manipur');
INSERT INTO `ratnacoi_zafrin`.`states` (`id`, `name`) VALUES (NULL, 'Meghalaya');
INSERT INTO `ratnacoi_zafrin`.`states` (`id`, `name`) VALUES (NULL, 'Mizoram');
INSERT INTO `ratnacoi_zafrin`.`states` (`id`, `name`) VALUES (NULL, 'Nagaland');
INSERT INTO `ratnacoi_zafrin`.`states` (`id`, `name`) VALUES (NULL, 'Odisha');
INSERT INTO `ratnacoi_zafrin`.`states` (`id`, `name`) VALUES (NULL, 'Punjab');
INSERT INTO `ratnacoi_zafrin`.`states` (`id`, `name`) VALUES (NULL, 'Rajasthan');
INSERT INTO `ratnacoi_zafrin`.`states` (`id`, `name`) VALUES (NULL, 'Sikkim');
INSERT INTO `ratnacoi_zafrin`.`states` (`id`, `name`) VALUES (NULL, 'Tamil Nadu');
INSERT INTO `ratnacoi_zafrin`.`states` (`id`, `name`) VALUES (NULL, 'Telangana');
INSERT INTO `ratnacoi_zafrin`.`states` (`id`, `name`) VALUES (NULL, 'Tripura');
INSERT INTO `ratnacoi_zafrin`.`states` (`id`, `name`) VALUES (NULL, 'Uttar Pradesh');
INSERT INTO `ratnacoi_zafrin`.`states` (`id`, `name`) VALUES (NULL, 'Uttarakhand');
INSERT INTO `ratnacoi_zafrin`.`states` (`id`, `name`) VALUES (NULL, 'West Bengal');
